name = "Scotch"
uuid = "c8656ae5-b689-4c12-92d5-de0ad806c81d"
authors = ["Keluaa <34173752+Keluaa@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
