name = "Scotch"
uuid = "c8656ae5-b689-4c12-92d5-de0ad806c81d"
authors = ["Keluaa <34173752+Keluaa@users.noreply.github.com> and contributors"]
version = "1.2.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
SCOTCH_jll = "a8d0f55d-b80e-548d-aff6-1a04c175f0f9"

[weakdeps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"

[extensions]
ScotchGraphs = "Graphs"
ScotchSimpleWeightedGraphs = ["Graphs", "SimpleWeightedGraphs"]

[compat]
Aqua = "0.7"
CEnum = "0.5"
Graphs = "1"
SCOTCH_jll = "7"
Test = "1"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Graphs", "SimpleWeightedGraphs", "Test"]
